plugins {
    id 'com.android.library'  // library 插件
}

android {
    namespace 'com.termux.shared'  // 命名空间
    compileSdk 34  // 升级到最新
    
    defaultConfig {
        minSdk 21
        targetSdk 34
        versionCode 1020
        versionName "0.119.0-beta.1"
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    
    // compile → implementation
    implementation 'io.github.zeroaicy:zeroaicy-util:1.0.0'
    implementation "androidx.appcompat:appcompat:1.6.1"
    implementation "androidx.annotation:annotation:1.8.0"
    implementation "androidx.core:core:1.13.0"
    implementation "com.google.android.material:material:1.12.0"
    implementation "com.google.guava:guava:33.3.0-android"
    implementation "io.noties.markwon:core:4.6.2"
    implementation "io.noties.markwon:ext-strikethrough:4.6.2"
    implementation "io.noties.markwon:linkify:4.6.2"
    implementation "io.noties.markwon:recycler:4.6.2"
    implementation "org.lsposed.hiddenapibypass:hiddenapibypass:6.1"
    implementation "androidx.window:window:1.4.0-alpha05"
    implementation "commons-io:commons-io:2.16.1"  // 升级到最新
    implementation project(":terminal-view")
    implementation "com.termux:termux-am-library:v2.0.0"
}