plugins {
    id 'com.android.library'
}

android {
    namespace 'com.termux.emulator'  // AGP 8.x 支持
    compileSdk 34  // 升级到最新
    
    defaultConfig {
        minSdk 21
        targetSdk 34
        versionCode 1020
        versionName "0.119.0-beta.1"
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

dependencies {
    // 修复 jar 路径
    compileOnly fileTree(dir: 'provider', include: ['*.jar'])
    
    implementation "androidx.annotation:annotation:1.8.0"
}